[package]
edition = "2021"
name = "fullstack-app"
version = "0.1.0"

[dependencies]
axum = "0.5.16"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.68"
tokio = {version = "1.0", features = ["full"]}
tower-http = {version = "0.3.4", features = ["cors"]}
